### ISSUE TITLE
no se pudo abrir el archivo <</etc/ssl/private/ssl-cert-snakeoil.key>>: Permiso denegado

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree#129]
Detectado en debian 7 y postgresql 9.1 al arrancar el servicio *postgresql*.
<pre>
# service postgresql start 
</pre>

Diagnóstico:
Los archivos *server.key* y *server.crt* no tienen el propietario adecuado. 

Solución propuesta:
<pre>
cd $(pg_lsclusters -h | awk '{print $6}')

rm server.crt
cp /etc/ssl/certs/ssl-cert-snakeoil.pem server.crt
chmod 600 server.crt
chown postgres:postgres server.crt

rm server.key
cp /etc/ssl/private/ssl-cert-snakeoil.key server.key
chmod 600 server.key
chown postgres:postgres server.key
</pre>

**Comment by jact** [comment]
A día de hoy, en nuestras pruebas de integración continua, esta incidencia no aplica en Debian 7.
