### ISSUE TITLE
Controlar la instalación del paquete migasfree-server 4.9

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree#146]
Debido a los cambios de migraciones de datos de Django 1.9, se requiere que **NO** se pueda instalar  el paquete migasfree-server_4.9 si hay  instalada una versión **anterior a la 4.8** en el equipo. 

Para instalar la 4.9 se requerirá por tanto:
* tener instalada la versión 4.8 de migasfre-server.
* ó bien no tener instalado el paquete migasfree-server.

**Comment by jact** [comment]
En paquetería RPM no es posible consultar la base de datos de los paquetes dentro del proceso de instalación de un paquete, por lo que esta incidencia no aplica a las distribuciones que se basan en esta paquetería.

Para el caso de paquetería Debian, se puede hacer lo que se comenta, pero tampoco es que sea la panacea. La razón de controlar la versión del paquete es que se está suponiendo que siempre se está en la mayor migración de la base de datos de migasfree posible. Si esto no es así (y un administrador puede moverse entre migraciones cuantas veces quiera), por más que se quiera controlar la versión *X* del paquete, no se va a obtener el resultado esperado: que las nuevas migraciones se lleven a cabo en el orden correcto en la actualización del software.
