### ISSUE TITLE
Fallo de creación de repositorio apt-get si algún paquete tiene una directiva incorrecta/vacía

### ISSUE THREAD

**Issue by jact** [migasfree/migasfree#152]
Y ya no se puede actualizar nada de dicho repositorio.

**Comment by agacias** [comment]
El error se ha producido en un debian jessie y usando apt-ftparchive para generar los repositorios.

El los clientes aparece el siguiente error
```
Error actualizando paquetes: E: Problem parsing dependency Suggests
E: Ocurrió un error al procesar googleearth (NewVersion2)
E: Problem with MergeList /var/lib/apt/lists/migasfree.red.zaragoza.es_repo_AZL-14_REPOSITORIES_dists_per-thirds_PKGS_binary-i386_Packages
E: No se pudieron analizar o abrir las listas de paquetes o el archivo de estado.
```
Se observa que la directiva Suggest esta vacía en el fichero Packages

Con el siguiente código para generar los repositorios ya no se produce dicho error, ya que en el fichero Packages generado ya no aparece la directiva Suggest.

```
cd %PATH%
mkdir -p %REPONAME%/PKGS/binary-i386/
mkdir -p %REPONAME%/PKGS/sources/
cd ..

dpkg-scanpackages -m dists/%REPONAME%/PKGS > dists/%REPONAME%/PKGS/binary-i386/Packages
gzip -9c dists/%REPONAME%/PKGS/binary-i386/Packages > dists/%REPONAME%/PKGS/binary-i386/Packages.gz

dpkg-scansources dists/%REPONAME%/PKGS > dists/%REPONAME%/PKGS/sources/Sources
gzip -9c dists/%REPONAME%/PKGS/sources/Sources > dists/%REPONAME%/PKGS/sources/Sources.gz


function SUM {
  echo $1
  _FILES=$(find  -type f| sed 's/^.\///'|sort)
  for _FILE in $_FILES
    do
     _SIZE=$(printf "%16d\n" $(ls -l $_FILE|cut -d ' ' -f5))
     _MD5=$($2 $_FILE|cut -d ' ' -f1) $()
     echo " $_MD5" "$_SIZE" "$_FILE"
    done
}

function create_release {
  _F="/var/tmp/Release"
  rm Release 2>/dev/null || :
  rm Release.gpg 2>/dev/null || :
  touch Release
  rm $_F 2>/dev/null || :
  echo "Architectures: i386 source" > $_F
  echo "Codename: %REPONAME%" >> $_F
  echo "Components: PKGS" >> $_F
  echo "Date: $(date -u '+%a, %d %b %Y %H:%M:%S UTC')"  >> $_F
  echo "Label: migasfree  Repository" >> $_F
  echo "Origin: migasfree" >> $_F
  echo "Suite: %REPONAME%" >> $_F
  SUM "MD5Sum:" "md5sum"  >> $_F
  SUM "SHA1:" "sha1sum"  >> $_F
  SUM "SHA256:" "sha256sum"  >> $_F
  SUM "SHA512:" "sha512sum"  >> $_F
  mv $_F Release
  gpg -u migasfree-repository --homedir /usr/share/migasfree-server/keys/.gnupg --clearsign -o InRelease Release
  gpg -u migasfree-repository --homedir /usr/share/migasfree-server/keys/.gnupg -abs -o Release.gpg Release
}

cd dists/%REPONAME%
create_release
```

**Comment by jact** [comment]
¿Y no se podría arreglar el código actual en lugar de cambiarlo todo?

**Comment by jact** [comment]
Nueva propuesta de código:

<pre>
_NAME=%REPONAME%
_ARCHS=("i386 amd64 source")
for _ARCH in ${_ARCHS[@]}
do
  cd %PATH%
  mkdir -p $_NAME/PKGS/binary-$_ARCH/
  cd ..

  dpkg-scanpackages -m dists/$_NAME/PKGS > dists/$_NAME/PKGS/binary-$_ARCH/Packages
  gzip -9c dists/$_NAME/PKGS/binary-$_ARCH/Packages > dists/$_NAME/PKGS/binary-$_ARCH/Packages.gz
done

function calculate_hash {
  echo $1
  _FILES=$(find  -type f | sed 's/^.\///' | sort)
  for _FILE in $_FILES
  do
    _SIZE=$(printf "%16d\n" $(ls -l $_FILE | cut -d ' ' -f5))
    _HASH=$($2 $_FILE | cut -d ' ' -f1) $()
    echo " $_HASH" "$_SIZE" "$_FILE"
  done
}

function create_deploy {
  _F=$(mktemp /var/tmp/deploy-XXXXX)

  rm Release 2>/dev/null || :
  rm Release.gpg 2>/dev/null || :
  touch Release
  rm $_F 2>/dev/null || :

  echo "Architectures: ${_ARCHS[@]}" > $_F
  echo "Codename: $_NAME" >> $_F
  echo "Components: PKGS" >> $_F
  echo "Date: $(date -u '+%a, %d %b %Y %H:%M:%S UTC')" >> $_F
  echo "Label: migasfree $_NAME repository" >> $_F
  echo "Origin: migasfree" >> $_F
  echo "Suite: $_NAME" >> $_F

  calculate_hash "MD5Sum:" "md5sum" >> $_F
  calculate_hash "SHA1:" "sha1sum" >> $_F
  calculate_hash "SHA256:" "sha256sum" >> $_F
  calculate_hash "SHA512:" "sha512sum" >> $_F

  mv $_F Release

  gpg -u migasfree-repository --homedir %KEYS%/.gnupg --clearsign -o InRelease Release
  gpg -u migasfree-repository --homedir %KEYS%/.gnupg -abs -o Release.gpg Release
}

cd dists/$_NAME
create_deploy
</pre>
