### ISSUE TITLE
Mostrar solamente las prestaciones del modelo de dispositivo

### ISSUE THREAD

**Issue by jact** [migasfree/migasfree#166]
En la actualidad, aparecen todas las disponibles de todos los modelos al agregar un dispositivo lógico en un dispositivo.

**Comment by jact** [comment]
Esto se podrá hacer teniendo en cuenta que si no se conoce el modelo del dispositivo (no se ha grabado aún), no se puede realizar el filtro en las prestaciones.

**Comment by agacias** [comment]
Al guardar un dispositivo se muestran sólo las prestaciones de la version de usuario.
