### ISSUE TITLE
Crear una vista para obtener CIDs dados unos valores de ordenador

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree#167]
Por ejemplo si pasamos el siguiente diccionario a la vista:
{"Name"="PC20751", MAC=" 5065f31e28a6"}
Debe devolver una lista de los CIDs de los ordenadores que tengan ese name **Y** esa mac (LÓGICA AND)

**Comment by jact** [comment]
Se está creando un _endpoint_ de API REST más genérico:

GET /api/v1/token/computers/

Parámetros:
* version__id
* status
* name
* platform
* created_at
* mac_address

Si la consulta tiene éxito, se devolverá un código de estado 200 y un JSON con la siguiente estructura:

<pre>
{
    "count":1207,
    "next":"http://localhost:1234/api/v1/token/computers/?page=2",
    "previous":null,
    "results":[
        {
            "id":388,
            "uuid":"7E4FD77A-CCCA-DA11-8131-003005C027A3",
            "name":"PC12391",
            "version":{"id":5,"name":"AZL-12"},
            "ip":"172.16.185.17",
            "status":"intended",
            "product":"EDITION P",
            "machine":"P",
            "mac_address":"003005C027A3",
            "cpu":"Intel Pentium 4  2.80GHz",
            "disks":1,
            "storage":80060424192,
            "ram":1073741824,
            "dateinput":"2010-12-01",
            "datehardware":"2016-04-04T08:29:00",
            "datelastupdate":"2016-04-20T10:54:13"
        },
        {
            "id":1429,
            "uuid":"B67285E8-BEF3-11DC-BBDA-C48F238F001C",
            "name":"PC15754",
            "version":{"id":5,"name":"AZL-12"},
            "ip":"172.16.86.23",
            "status":"intended",
            "product":"HP Compaq dc5700 Small Form Factor (EW290AV)",
            "machine":"P",
            "mac_address":"001CC48F238F",
            "cpu":"Intel Core2 Duo      E4600   2.40GHz",
            "disks":1,
            "storage":80026361856,
            "ram":1073741824,
            "dateinput":"2012-10-19",
            "datehardware":"2016-03-28T08:24:46",
            "datelastupdate":"2016-04-20T08:37:15"
        }
    ]
}
</pre>

Este _endpoint_ necesita autentificación. Esta se consigue a través de un _header_ con un token que devolverá este otro _endpoint_:

POST /token_auth/ {"username":"xxxx","password":"xxxx"}

El _header_ tiene la forma:

"Authorization: Token 8e34a0eff0790114d0c176714bb61cfc200e9770"

**Comment by jact** [comment]
Ejemplo de uso con _curl_ en línea de comando:

<pre>
$ curl -X POST -H "Content-Type: application/json" -d '{"username":"xxxx","password":"xxxx"}' http://localhost:1234/token-auth/
{"token":"d9a37fb00dc6413bbd2269cc422af8d25d34bbae"}

$ curl -H "Authorization: Token d9a37fb00dc6413bbd2269cc422af8d25d34bbae" -H "Content-Type: application/json" "http://localhost:1234/api/v1/token/computers/?name=PC21530&mac_address=5065F31EA5CC"
{"count":1,"next":null,"previous":null,"results":[{"id":4065,"uuid":"51A76E80-818C-11E5-BA2C-5065F31EA5CC","name":"PC21530","version":{"id":16,"name":"AZL-14"},"ip":"172.16.69.135","status":"intended","product":"HP ProDesk 600 G1 SFF (C8T89AV)","machine":"P","mac_address":"5065F31EA5CC","cpu":"Intel Core i5-4590   3.30GHz","disks":2,"storage":620141985792,"ram":4294967296,"dateinput":"2016-01-12","datehardware":"2016-04-13T07:44:51","datelastupdate":"2016-04-20T07:44:36"}]}
</pre>

**Comment by jact** [comment]
La lista de _endpoints_ disponibles en la API REST se podrán consultar en la URL */docs* del servidor migasfree.
