### ISSUE TITLE
Crear un vista para cambiar el estado de los ordenadores

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree#168]
Con el fin de poder cambiar el estado de los ordenadores desde aplicaciones externas.
Para cambiar el estado a un equipo desde esta vista será necesario pasar el CID y el nuevo ESTADO.
Sera necesario también estar autenticado.

**Comment by jact** [comment]
Siguiendo con lo comentado en la incidencia #167, se va a crear otro _endpoint_ en la API REST para esta tarea:

POST /api/v1/token/computers/{pk}/status/ {"status":"xxx"}
donde los posibles valores para _status_ son:
* "available"
* "reserved"
* "unsubscribed"
* "unknown"
* "intended"

En caso de éxito, devolverá un código de estado 200 y la información del ordenador en formato JSON. También requerirá un _token_ de autentificación.

**Comment by jact** [comment]
Ejemplo de uso con _curl_ en línea de comando:

<pre>
$ curl -X POST -H "Content-Type: application/json" -d '{"username":"xxxx","password":"xxxx"}' http://localhost:1234/token-auth/
{"token":"d9a37fb00dc6413bbd2269cc422af8d25d34bbae"}

$ curl -H "Authorization: Token d9a37fb00dc6413bbd2269cc422af8d25d34bbae" -H "Content-Type: application/json" -X POST -d '{"status": "reserved"}' http://localhost:1234/api/v1/token/computers/4065/status/
{"id":4065,"uuid":"51A76E80-818C-11E5-BA2C-5065F31EA5CC","name":"PC21530","version":{"id":16,"name":"AZL-14"},"ip":"192.168.1.33","status":"reserved","product":"HP ProDesk 600 G1 SFF (C8T89AV)","machine":"P","mac_address":"5065F31EA5CC","cpu":"Intel Core i5-4590   3.30GHz","disks":2,"storage":620141985792,"ram":4294967296,"dateinput":"2016-01-12","datehardware":"2016-04-13T07:44:51","datelastupdate":"2016-04-20T07:44:36"}
</pre>
