### ISSUE TITLE
Problemas de rendimiento en la página de ordenadores actualizándose/retrasados

### ISSUE THREAD

**Issue by sannacho** [migasfree/migasfree#171]
Version 4.8 server. Hemos detectado (servidor en producción y en pruebas) que al consultar el computer delayed o updating now, apache se "come toda memoria disponible en el sistema  y no la libera al navegar a otras páginas o incluso salir de la sesión
Número de equipos delayed: 1100 en producción y 800 en MV
Puede ser que esté relacionado el problema con estamos detectando que hay varios equipos (la tercera parte ya del total) que se expira la conexión en algún punto de la actualización

**Comment by agacias** [comment]
Gracias por reportar el error. Nos ponemos a trabajar en ello.
Puedes temporalmente y hasta que solucionemos el bug **deshabilitar**:  "Configuración-Comprobación-Ordenadores actualizándose ahora y ordenadores retrasados".
¿ Puedes verificar que con estas comprobaciones ya no se produce fuga de memoria?

**Comment by agacias** [comment]
más información: http://soporte.vitalinux.educa.aragon.es/issues/217

**Comment by sannacho** [comment]
Hola Alberto...Deshabilitando los computer delayed, al no poder "ver" dicha información, de momento parece que se mantiene ok el server....
Observaré si ésto también repercute en que los clientes no den los errores que estamos teniendo de expiración en la comunicación con el servidor en alguna parte del proceso de actualización

**Comment by jact** [comment]
Al investigar con más detenimiento el rendimiento de la página, se ha observado que hay demasiado tráfico entre el servidor y la base de datos para obtener los datos que se muestran.

Se han eliminado consultas y campos innecesarios a la hora de recuperar los datos del servidor de base de datos. Además, se ha separado mejor lo que es presentación de contenido a la hora de maquetar la página de respuesta.
