### ISSUE TITLE
Error en el proceso de migración de 4.8 a 4.10

### ISSUE THREAD

**Issue by sannacho** [migasfree/migasfree#172]
Hola de nuevo. Estoy haciendo pruebas para hacer el upgrade del server de la versión 4.8 a la 4.10 y aparece un problema al final (entiendo cuando migra la BD de 4.8 a 4.10). Os indico los pasos realizados y los resultados:
Paritda: Maquina Virtual de Test:
* Debian 8 actualizado (salvo el hold de python-django propio de la version 4.8 de server) y restaurado con toda la conf del actual de producción (migasfree server en 4.8)
  * Restore de la BD
  * Restore de claves de repos y de comunicación con clientes, 
  * Restore del archivo de con de /etc/migasfree-server/settings.py

Pasos realizados:
1. Añado el repositorio nuevo: 
echo "deb http://migasfree.org/pub wheezy PKGS" > /etc/apt/sources.list.d/migasfree.list
2. Añado la clave del repo del server
wget -O - http://migasfree.org/pub/gpg_key | apt-key add -
3. Descongelo el python-django
apt-mark unhold python-django
4. Instalar
apt-get update
apt-get -y install --no-install-recommends migasfree-server

Todo ok, hasta la instalación...:-(
root@migasTEST:~# apt-get -y install --no-install-recommends migasfree-server
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
migasfree-server ya está en su versión más reciente.
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 1 no actualizados.
root@migasTEST:~# apt-get update
Des:1 http://migasfree.org wheezy InRelease [6.936 B]
Des:2 http://security.debian.org jessie/updates InRelease [63,1 kB]                                       
Des:3 http://migasfree.org wheezy/PKGS amd64 Packages [7.786 B]                          
Ign http://ftp.fi.debian.org jessie InRelease                                                                   
Des:4 http://security.debian.org jessie/updates/main Sources [133 kB]                                           
Des:5 http://ftp.fi.debian.org jessie-updates InRelease [142 kB]                      
Des:6 http://security.debian.org jessie/updates/main amd64 Packages [241 kB]                
Ign http://migasfree.org wheezy/PKGS Translation-es_ES                                      
Ign http://migasfree.org wheezy/PKGS Translation-es                                          
Ign http://migasfree.org wheezy/PKGS Translation-en                                          
Des:7 http://security.debian.org jessie/updates/main Translation-en [131 kB]         
Obj http://ftp.fi.debian.org jessie Release.gpg                                                                    
Des:8 http://ftp.fi.debian.org jessie-updates/main Sources [14,1 kB]
Des:9 http://ftp.fi.debian.org jessie-updates/main amd64 Packages/DiffIndex [3.472 B]
Des:10 http://ftp.fi.debian.org jessie-updates/main Translation-en/DiffIndex [1.720 B]
Obj http://ftp.fi.debian.org jessie Release          
Obj http://ftp.fi.debian.org jessie/main Sources
Obj http://ftp.fi.debian.org jessie/main amd64 Packages            
Obj http://ftp.fi.debian.org jessie/main Translation-es                
Obj http://ftp.fi.debian.org jessie/main Translation-en                
Descargados 744 kB en 3s (228 kB/s)                                    
Leyendo lista de paquetes... Hecho
root@migasTEST:~# apt-get -y install --no-install-recommends migasfree-server
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
El paquete indicado a continuación se instaló de forma automática y ya no es necesario.
  python-django-south
Utilice «apt-get autoremove» para eliminarlo.
Se instalarán los siguientes paquetes extras:
  python-diff-match-patch python-django python-django-admin-bootstrapped python-django-ajax-selects python-django-autocomplete-light
  python-django-bootstrap3 python-django-import-export python-tablib
Se instalarán los siguientes paquetes NUEVOS:
  python-diff-match-patch python-django-admin-bootstrapped python-django-autocomplete-light python-django-bootstrap3
  python-django-import-export python-tablib
Se actualizarán los siguientes paquetes:
  migasfree-server python-django python-django-ajax-selects
3 actualizados, 6 nuevos se instalarán, 0 para eliminar y 1 no actualizados.
Se necesita descargar 6.048 kB de archivos.
Se utilizarán 12,7 MB de espacio de disco adicional después de esta operación.
Des:1 http://migasfree.org/pub/ wheezy/PKGS migasfree-server all 4.10-1 [940 kB]
Des:2 http://ftp.fi.debian.org/debian/ jessie/main python-tablib all 0.9.11-2 [256 kB]    
Des:3 http://ftp.fi.debian.org/debian/ jessie/main python-diff-match-patch all 20121119-1 [24,2 kB]
Des:4 http://migasfree.org/pub/ wheezy/PKGS python-django all 1.9.3-1 [3.980 kB]          
Des:5 http://migasfree.org/pub/ wheezy/PKGS python-django-ajax-selects all 1.4.2-1 [32,0 kB]
Des:6 http://migasfree.org/pub/ wheezy/PKGS python-django-autocomplete-light all 3.1.1-1 [379 kB]
Des:7 http://migasfree.org/pub/ wheezy/PKGS python-django-bootstrap3 all 6.2.2-1 [22,7 kB]
Des:8 http://migasfree.org/pub/ wheezy/PKGS python-django-admin-bootstrapped all 2.5.7-1 [376 kB]
Des:9 http://migasfree.org/pub/ wheezy/PKGS python-django-import-export all 0.4.0-1 [37,4 kB]
Descargados 6.048 kB en 2s (2.480 kB/s)           
Leyendo lista de cambios... Hecho.
Seleccionando el paquete python-tablib previamente no seleccionado.
(Leyendo la base de datos ... 44933 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../python-tablib_0.9.11-2_all.deb ...
Desempaquetando python-tablib (0.9.11-2) ...
Preparando para desempaquetar .../migasfree-server_4.10-1_all.deb ...
Desempaquetando migasfree-server (4.10-1) sobre (4.8-1) ...
Preparando para desempaquetar .../python-django_1.9.3-1_all.deb ...
Desempaquetando python-django (1.9.3-1) sobre (1.6.11-1) ...
Preparando para desempaquetar .../python-django-ajax-selects_1.4.2-1_all.deb ...
Desempaquetando python-django-ajax-selects (1.4.2-1) sobre (1.3.3-1) ...
Seleccionando el paquete python-django-autocomplete-light previamente no seleccionado.
Preparando para desempaquetar .../python-django-autocomplete-light_3.1.1-1_all.deb ...
Desempaquetando python-django-autocomplete-light (3.1.1-1) ...
Seleccionando el paquete python-django-bootstrap3 previamente no seleccionado.
Preparando para desempaquetar .../python-django-bootstrap3_6.2.2-1_all.deb ...
Desempaquetando python-django-bootstrap3 (6.2.2-1) ...
Seleccionando el paquete python-django-admin-bootstrapped previamente no seleccionado.
Preparando para desempaquetar .../python-django-admin-bootstrapped_2.5.7-1_all.deb ...
Desempaquetando python-django-admin-bootstrapped (2.5.7-1) ...
Seleccionando el paquete python-diff-match-patch previamente no seleccionado.
Preparando para desempaquetar .../python-diff-match-patch_20121119-1_all.deb ...
Desempaquetando python-diff-match-patch (20121119-1) ...
Seleccionando el paquete python-django-import-export previamente no seleccionado.
Preparando para desempaquetar .../python-django-import-export_0.4.0-1_all.deb ...
Desempaquetando python-django-import-export (0.4.0-1) ...
Procesando disparadores para python-support (1.0.15) ...
Configurando python-tablib (0.9.11-2) ...
Configurando python-django (1.9.3-1) ...
Configurando python-django-ajax-selects (1.4.2-1) ...
Configurando python-django-autocomplete-light (3.1.1-1) ...
Configurando python-django-bootstrap3 (6.2.2-1) ...
Configurando python-django-admin-bootstrapped (2.5.7-1) ...
Configurando python-diff-match-patch (20121119-1) ...
Configurando python-django-import-export (0.4.0-1) ...
Configurando migasfree-server (4.10-1) ...
[ ok ] Starting postgresql (via systemctl): postgresql.service.
Operations to perform:
  Apply all migrations: admin, contenttypes, sessions, auth, server
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... FAKED
  Applying auth.0001_initial... FAKED
  Applying admin.0001_initial... FAKED
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying server.0001_initial... FAKED
  Applying server.0002_4_9_changes... OK
  Applying server.0003_4_10_changes... OK
  Applying server.0004_4_10_hardware_resume...Traceback (most recent call last):
  File "/usr/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/lib/python2.7/dist-packages/migasfree/server/migrations/0004_4_10_hardware_resume.py", line 14, in insert_initial_hardware_resume
    computer.update_hardware_resume()
  File "/usr/lib/python2.7/dist-packages/migasfree/server/models/computer.py", line 285, in update_hardware_resume
    self.cpu = HwNode.get_cpu(self.id)
  File "/usr/lib/python2.7/dist-packages/migasfree/server/models/hw_node.py", line 245, in get_cpu
    product = product.replace(item, '')
AttributeError: 'NoneType' object has no attribute 'replace'
createdb: falló la creación de la base de datos:
ERROR:  la base de datos «migasfree» ya existe
dpkg: error al procesar el paquete migasfree-server (--configure):
 el subproceso instalado el script post-installation devolvió el código de salida de error 1
Se encontraron errores al procesar:
 migasfree-server
E: Sub-process /usr/bin/

Saludos
-- nacho

**Comment by jact** [comment]
Alguno de los equipos no ha recogido bien la información del _hardware_ y hay campos que contienen nulos. Se ha añadido una condición para contemplar esta posibilidad.
