### ISSUE TITLE
Añadir endpoint a la API para que se puedan añadir dispositivos lógicos a un ordenador

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree#175]

**Comment by jact** [comment]
Obtener los dispositivos lógicos de un ordenador:

`curl -H "Authorization: Token 7da8ec..." -H "Content-Type: application/json" "http://<server>/api/v1/token/computers/<pk>/logical-devices/"

[{"id":112,"device":{"id":6,"name":"19940"},"feature":{"id":2,"name":"Color"},"name":""},{"id":7,"device":{"id":6,"name":"19940"},"feature":{"id":1,"name":"BN"},"name":""}]`

Añadir dispositivos lógicos a un ordenador:

`curl --request PATCH -H "Authorization: Token 7da8ec..." -H "Content-Type: application/json" -d '[7,112]' "http://<server>/api/v1/token/computers/<pk>/logical-devices/"`

Reemplazar dispositivos lógicos de un ordenador:

`curl --request PUT -H "Authorization: Token 7da8ec..." -H "Content-Type: application/json" -d '[7,112]' "http://<server>/api/v1/token/computers/<pk>/logical-devices/"`
