### ISSUE TITLE
Añadir información tabular a las estadísticas

### ISSUE THREAD

**Issue by jact** [migasfree/migasfree#176]
Para que sea más fácil la exportación de los datos que se muestran en las estadísticas, es necesario añadir dicha información.

**Comment by jact** [comment]
La librería pygal permite añadir los datos tabulares de forma muy sencilla. Habría que sustituir la actual librería flot por pygal.

**Comment by agacias** [comment]
En resoluciones de monitor 16:9 no se ven completamente las gráficas en la pantalla.
