### ISSUE TITLE
Catálogo de aplicaciones

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree#177]
Sería interesante tener un catálogo de aplicaciones para que:
* Se muestren **sólo** las apps más relevantes (y controladas) para la organización.
* El usuario pueda instalar manualmente una app aunque no tenga permisos de administrador.
* Ordenadas por puntuación (importancia para la organización).
* Categorizadas
* Similar a https://apps.ubuntu.com

**Comment by jact** [comment]
Se proporcionan 2 _endpoints_ nuevos para la API REST del proyecto, con la intención de ser consumidas por otra aplicación en los clientes:
* /api/v1/public/catalog/apps/
* /api/v1/public/catalog/apps/<pk>/

Las aplicaciones del catálogo se pueden gestionar a través del IU del proyecto (en el apartado **Configuración**). Si una misma aplicación está disponible en varias versiones y se quiere añadir al catálogo, habrá que agregar una entrada diferente por versión.

**Comment by jact** [comment]
![apps_catalog_preview](https://cloud.githubusercontent.com/assets/251908/17328640/17dd879c-58bf-11e6-82f5-118239f11ea3.png)

Detalle de una aplicación del catálogo.

**Comment by jact** [comment]
Ejemplo de llamada a la API:

GET /api/v1/public/catalog/apps/?level=U&version__name=AZL-12

```
{
    "count": 2,
    "next": null,
    "previous": null,
    "results": [
        {
            "category": {
                "id": 3,
                "name": "Herramientas de desarrollo"
            },
            "score": 4,
            "name": "Bluefish",
            "version": {
                "id": 5,
                "name": "AZL-12"
            },
            "level": "U",
            "packages_to_install": "bluefish",
            "icon": "http://localhost:1234/repo/catalog_icons/bluefish.png",
            "id": 2,
            "description": "# título\r\n\r\npárrafo\r\n\r\n* item 1\r\n* item 2"
        },
        {
            "category": {
                "id": 3,
                "name": "Herramientas de desarrollo"
            },
            "score": 5,
            "name": "Geany",
            "version": {
                "id": 5,
                "name": "AZL-12"
            },
            "level": "U",
            "packages_to_install": "geany",
            "icon": "http://localhost:1234/repo/catalog_icons/geany.png",
            "id": 1,
            "description": "blah, blah"
        }
    ]
}
```
