### ISSUE TITLE
Se necesita endpoint login

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree#191]

**Comment by jact** [comment]
Se añadirá el _endpoint_ computers/<pk>/sync/, que devolverá la siguiente información:

<pre>
            {
                "date": "Y-m-d H:M:s",
                "user": {
                    "id": x,
                    "name": "xxx",
                    "fullname": "xxxxx"
                },
                "attributes": [
                    {
                        "id": x,
                        "value": "xxx",
                        "description": "xxxxx",
                        "total_computers"; xx,
                        "property_att": {
                            "id": x,
                            "prefix": "xxx"
                        }
                    },
                    ...
                ]
            }
</pre>
