### ISSUE TITLE
Cambio de estado y etiquetas

### ISSUE THREAD

**Issue by sannacho** [migasfree/migasfree#217]
Cuando se da de baja un equipo se supone que debería realizar varias acciones según la documentación, entre ellas la de eliminar la asignación de todas sus etiquetas. A la hora de dar de baja el equipo, si nos fijamos en las etiquetas que tenía el equipo vemos que el equipo sigue estando como uno de los equipos etiquetados.

Desde el cliente no se puede comprobar ya que en el momento de dar de baja se imposibilita la comunicación con migas (comportamiento deseado e incorporado en esta versión: 4.13).

Indicar que la designación de los repositorios, fallas... sí que se hace, pero no así la de etiquetas. No sabemos si es comportamiento deseado o no en el caso de las etiquetas, pero si eso sería conveniente indicarlo en la documentación.

**Comment by agacias** [comment]
Es un bug. Está programado pero no funciona:

https://github.com/migasfree/migasfree/blob/4.13/migasfree/server/models/computer.py#L449
