### ISSUE TITLE
Bug: Cambiar nombre a una etiqueta

### ISSUE THREAD

**Issue by sannacho** [migasfree/migasfree#222]
Versión del servidor: 4.13, actualizado con los parches para los errores indicados en #215 sobre migasfree-tags y #217 de cambio de estado.
A la hora de modificar el nombre de una etiqueta el servidor salta un error y lógicamente no provoca el cambio

**Comment by sannacho** [comment]
Tampoco nos deja crear nuevas etiquetas!
Probando a revertir los cambios realizados en #217 se comprueba que funciona correctamente tanto la creación de nuevas etiquetas como el cambio de nombre, por lo tanto es un problema que se introduce con los cambios sugeridos en dicha incidencia.
Volvemos al estado previo de momento (es mas importante crear y modificar etiquetas de momento)

**Comment by jact** [comment]
En el fichero models/computer.py, reemplaza la última función por esta otra:

<pre>
@receiver(m2m_changed, sender=Computer.tags.through)
def tags_changed(sender, instance, action, **kwargs):
    if hasattr(instance, 'status'):
        if instance.status in ['available', 'unsubscribed'] and action == 'post_add':
            instance.tags.clear()
</pre>

En la versión en desarrollo, el código de la incidencia #217 no falla, pero hay mucho cambio de modelo de datos entre la 4.13 y lo que hay en estos momentos...

Dime si esto soluciona todo el problema.

**Comment by sannacho** [comment]
Funciona!
Gracias Jose Antonio.
