### ISSUE TITLE
Propuesta para obtener informacion de errores agrupada

### ISSUE THREAD

**Issue by sannacho** [migasfree/migasfree#226]
Los datos relacionados de una etiqueta son varios e interesantes: conjunto de atributos, ordenadores, logins, Definiciones de fallas....pero no tenemos opción de saber errores que se han producido en los equipos que tienen dicha etiqueta. Dicha información tampoco se puede obtenter desde la pantalla de errores...En la explotación que hacemos de migas, nos vendría de perlas poder obtener dicha información en alguna de éstas formas ya que nos permite ver si se producen los errores agrupados en un centro...

**Comment by jact** [comment]
Debido a restricciones de Django, no se puede hacer un filtro de un campo _many to many_ relacionado que no esté definido en el filtro del modelo. Y definir el filtro de etiquetas en los errores... es demasiado arbitrario...

De todas formas, se puede hacer una SQL contra la base de datos para obtener esa información.
