### ISSUE TITLE
Añadir más comprobaciones (despliegues)

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree#239]
* Despliegues activos (con calendario, pero no completado) (server) (info) -> para relacionar errores con estos despliegues
* Despliegues con calendario completado (server) (warning) -> para pasarlos a permanentes o borrarlos

**Comment by jact** [comment]
Por el momento, la URL a la que redirigen estas nuevas comprobaciones es la misma: despliegues habilitados con calendario asignado. No hay un campo en la BD que indique si el despliegue está o no completado, por lo que no se puede filtrar en la página de despliegues.

Queda pendiente crear ese campo, y realizar alguna tarea en segundo plano para que lo actualice.
