### ISSUE TITLE
tea4cups wrapper

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree#242]
Se solicita que algunas impresoras puedan hacer uso de tea4cups.

Una posible solución sería:

- En la conexión *x*, añadimos un campo más llamado **CUPSWRAPPER**

A partir de este momento, en los dispositivos con conexión *x* aparece el campo CUPSWRAPPER para que pueda ser asignado con el wrapper: **"tea4cups"**

![image](https://user-images.githubusercontent.com/247068/32989284-8d63e9ce-cd13-11e7-9b49-8a2cf6c7f519.png)

Esto requeriría **modificar migasfree-client** para que añada el campo CUPSWRAPPER al inicio del URI del dispositivo.

**Comment by jact** [comment]
Cuidado con añadir en el *wrapper* símbolos como ':' o '/'. Si se necesitan, los añadirá el cliente al construir el URI del dispositivo.
