### ISSUE TITLE
Resetear o recuperar contraseña del usuario

### ISSUE THREAD

**Issue by amartinr1977** [migasfree/migasfree#256]
Al implementar y hacer uso de dominios en la gestión de Migasfree el número de usuarios que va a acceder a la plataforma de gestión va a ser mayor ... ¿Tenéis previsto en el login de Migasfree el típico enlace de "Has olvidado la contraseña ...."? ¿El poder resetear de una forma sencilla la contraseña mandando a la cuenta de email del usuario la nueva password?

**Comment by agacias** [comment]
Ejemplo para la configuración de email ( /var/lib/migasfree/${FQDN}/conf ):

```
EMAIL_USE_TLS = True
EMAIL_HOST = 'webmail.mydomain.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = "myaccount@mydomain.com"
EMAIL_HOST_PASSWORD = "mypassword"
DEFAULT_FROM_EMAIL = "My Domain <noreply@mydomain.com>"
```

**Comment by agacias** [comment]
Se produce el siguiente error:
```
TemplateSyntaxError at /reset/Mw/set-password/
'future' is not a registered tag library. Must be one of:
```

que desaparece eliminando **{% load url from future %}** 
en:
/usr/local/lib/python2.7/dist-packages/django_admin_bootstrapped/templates/registration/password_reset_confirm.html
y
/usr/local/lib/python2.7/dist-packages/django_admin_bootstrapped/templates/registration/password_reset_complete.html
