### ISSUE TITLE
Simulación de sincronización no muestra todos los repositorios

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree#262]
Ocurre cuando un repositorio tiene asignado un atributo de tipo lista.

Revisar la llamada a **upload_computer_info**, en concreto como se está generando el elemento **attributes**. 

https://github.com/migasfree/migasfree/blob/78e0cb42e1336fd5a1df4656f26d43bd2d220999/migasfree/server/views/computer.py#L208

**Comment by jact** [comment]
También ocurre cuando un despliegue tiene asignado un atributo de tipo añadir por la derecha o por la izquierda.

No se están devolviendo todos los valores de esos tipos de atributos, por lo que la simulación puede engañar.
