### ISSUE TITLE
Conjunto de atributos en un conjunto

### ISSUE THREAD

**Issue by sannacho** [migasfree/migasfree#271]
Si se define un conjunto de atributos (SET-A), que contiene entre otros atributos otro conjunto(SET-B), no funciona como se espera. Por ejemplo, si se define una falla y se pone como atributo incluído el SET-A, la falla no se ejecuta en los CID's que en SET-B.

**Comment by agacias** [comment]
¿Puede estar ocurriendo que inicialmente los equipos no pertenezcan al SET-B y es entonces hasta la segunda sincronización que no os esté funcionando?

**Comment by agacias** [comment]
De acuerdo. Intentaremos reproducir el error. Gracias

**Comment by agacias** [comment]
El error se lleva arrastrando desde la versión 4.14.

Esta relacionado  con  la issue #212

Se hizo entonces una refactorización de los metodos get_sets y process de la clase AttributeSet.  

https://github.com/migasfree/migasfree/commit/0c0246dbeee1b504f55fd8540900514bdd960f86#diff-c1d1454dcbe3a84d95dc595252657f53 

https://github.com/migasfree/migasfree/commit/73245c190eb6b4b9a45080f1b303f01773517adc

**Comment by jact** [comment]
No funciona bien con varios niveles de dependencias.

**Comment by agacias** [comment]
Se produce un errror 500 al añadir  y guardar un **nuevo conjunto de atributos**  si asignamos otro conjunto en incluidos o excluidos.
