### ISSUE TITLE
Respuesta del servidor Django al actualizar un despliegue

### ISSUE THREAD

**Issue by sannacho** [migasfree/migasfree#276]
Hemos detectado que a la hora de guardar cambios en un repositorio que contiene varios paquetes disponibles para su instalación, la respuesta que aparece con el listado de paquetes disponibles y el éxito de la operación (que aparece en verde) no se refleja en la "pantalla de salida", sino en navegaciones posteriores...quedando a veces sin saber si se ha guardado correctamente o no.
Si en lugar de dar a guardar le damos a guardar y continuar si que lo pinta en la misma pantalla.

**Comment by jact** [comment]
En la versión 4.17 del servidor, hemos actualizado Django a la versión 1.11.18, pero mucho me temo que no va a arreglar este problema.

**Comment by jact** [comment]
Hemos vuelto a actualizar a Django 1.11.20, pero el problema persiste. Al ser un problema del _framework_, no podemos hacer nada al respecto.
