### ISSUE TITLE
Reducir las llamadas a las alertas

### ISSUE THREAD

**Issue by jact** [migasfree/migasfree#280]
Ahora mismo, en cada página de la aplicación, cada 10 segundos, se está llamando al cálculo de las alertas. Esto puede repercutir negativamente en el rendimiento del servidor si hay muchos clientes web que accedan a él.

Se trata de reducir este número de llamadas.

**Comment by jact** [comment]
El comportamiento que tendrá a partir de ahora es el siguiente:

* Cuando se consulte cada página de la aplicación, se hará una llamada a la URL de las alertas.

* Si se pulsa sobre las alertas, se hará otra llamada y, mientras el desplegable esté abierto, se refrescarán cada 10 segundos. En el momento en el que el despliegue se cierre, no habrá más peticiones de alertas.

Este comportamiento es aplicable a todas las páginas de la aplicación, excepto cuando se esté viendo los grupos de usuarios. Al haber una carga adicional de la librería jquery en estas páginas, se están sobrescribiendo métodos de javascript que eliminan el comportamiento programado.

**Comment by agacias** [comment]
Se comprueba que cada 10 segundos (con el desplegable abierto) se hace efectivaente la llamada a alertas (/alerts) pero **no refresca** el contenido del desplegable.
