### ISSUE TITLE
Problema con CORS (cross-domain)

### ISSUE THREAD

**Issue by amartinr1977** [migasfree/migasfree#286]
Hola,
Tal como hemos comprobado esta mañana, os recuerdo los pasos para dar solución al CORS en las aplicaciones Web:

0) Seguir la documentación de Django: https://github.com/ottoyiu/django-cors-headers
1) pip install django-cors-headers
2) vi /usr/local/lib/python2.7/dist-packages/migasfree/settings/base.py
INSTALLED_APPS = (
    ...
    'corsheaders',
    ...
)

MIDDLEWARE = [  # Or MIDDLEWARE_CLASSES on Django < 1.10
    ...
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    ...
]
3) circusctl restart migasfree-server

Por otro lado será necesario configurar las cabeceras en el servicio nginx:
4) add_directives.conf del sites-available:
add_header 'Access-Control-Allow-Origin' "$http_origin";
add_header 'Access-Control-Allow-Credentials' 'true';
add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With';

Pudiendo poner listas "blancas" en la configuración de Django tal como se explica en https://github.com/ottoyiu/django-cors-headers

**Comment by jact** [comment]
Se añade django-cors-headers como aplicación al proyecto migasfree.

Queda pendiente hacer las modificaciones en migasfree-docker para añadir las líneas de configuración de Nginx.

En el fichero */etc/migasfree-server/settings.py* se podrán configurar las listas blancas de CORS sin necesidad de modificar el contenedor.
